services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-2
    environment:
      MYSQL_ROOT_PASSWORD: 2002
    ports:
      - "3316:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: